### ISSUE TITLE
Error in data.yml

### ISSUE THREAD

**Issue by marcelcastrobr** [hnky/pytorch-workshop#1]
HI,
  I realized that your current data.yml is not working for me.
  The following data.yml works for me:
**$schema: https://azuremlschemas.azureedge.net/latest/dataset.schema.json
name: LegoSimpsons
version: 1
local_path: ./data**

  By the way, since azure cli was complaining about deprecation, you probably could also update the command line to:
**az ml dataset create -f data.yml**

**Comment by hnky** [comment]
Thanks it should work now :D
